# Generated by Django 4.1.7 on 2023-03-08 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(help_text='File Must Be in PDF format', upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
