# Generated by Django 4.1.7 on 2023-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='docs',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
